# Coding Practice Session 2
## Creating Numpy Arrays

In [1]:
import numpy as np

### 1-Dimensional arrays

In [6]:
arr = np.array([1, 2, 3, 4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

In [10]:
arr_tuple = np.array((5, 10, 15))
arr_tuple

array([ 5, 10, 15])

In [14]:
np.array(range(1, 15, 2))

array([ 1,  3,  5,  7,  9, 11, 13])

In [20]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(5, 15, 75, endpoint=False)

array([ 5.        ,  5.13333333,  5.26666667,  5.4       ,  5.53333333,
        5.66666667,  5.8       ,  5.93333333,  6.06666667,  6.2       ,
        6.33333333,  6.46666667,  6.6       ,  6.73333333,  6.86666667,
        7.        ,  7.13333333,  7.26666667,  7.4       ,  7.53333333,
        7.66666667,  7.8       ,  7.93333333,  8.06666667,  8.2       ,
        8.33333333,  8.46666667,  8.6       ,  8.73333333,  8.86666667,
        9.        ,  9.13333333,  9.26666667,  9.4       ,  9.53333333,
        9.66666667,  9.8       ,  9.93333333, 10.06666667, 10.2       ,
       10.33333333, 10.46666667, 10.6       , 10.73333333, 10.86666667,
       11.        , 11.13333333, 11.26666667, 11.4       , 11.53333333,
       11.66666667, 11.8       , 11.93333333, 12.06666667, 12.2       ,
       12.33333333, 12.46666667, 12.6       , 12.73333333, 12.86666667,
       13.        , 13.13333333, 13.26666667, 13.4       , 13.53333333,
       13.66666667, 13.8       , 13.93333333, 14.06666667, 14.2 

In [26]:
np.linspace(1, 5, 23)

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        , 3.18181818, 3.36363636, 3.54545455,
       3.72727273, 3.90909091, 4.09090909, 4.27272727, 4.45454545,
       4.63636364, 4.81818182, 5.        ])

In [27]:
np.linspace(0, 5, 10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### 2-Dimensional arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.size

9

In [31]:
arr = np.zeros((5, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr.shape

(5, 3)

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
arr = np.ones((4, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
arr.shape

(4, 6)

In [40]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.eye(4, 3, -2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
np.diag([1, 2, 3, 4], 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

### Higher-Dimensional arrays

In [57]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [58]:
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [59]:
arr.shape

(3, 2, 2)

In [60]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [61]:
np.ones((3, 3, 6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [62]:
np.zeros((2, 3, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [65]:
np.ones((3, 2, 4, 4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

### arrays with specific data types

In [66]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [68]:
np.array([2, 4, 8], dtype=np.float16)

array([2., 4., 8.], dtype=float16)

In [72]:
np.array([345, 854, 900], dtype=np.uint16)

array([345, 854, 900], dtype=uint16)

In [79]:
arr = np.array([5 + 2j, 8j, 10])

In [80]:
arr

array([ 5.+2.j,  0.+8.j, 10.+0.j])

In [81]:
arr.dtype

dtype('complex128')

In [83]:
np.array([-10, -20, 5], dtype=np.int8)

array([-10, -20,   5], dtype=int8)

In [84]:
np.array([5, 65, 74], dtype="uint8")

array([ 5, 65, 74], dtype=uint8)

### random number generation

In [ ]:
np.random.rand()  # chooses from uniform distribution

0.7543767709390526

In [88]:
np.random.rand(3)

array([0.42600095, 0.54628481, 0.09968876])

In [ ]:
np.random.rand(2, 3)

array([[0.56789523, 0.42880115, 0.09667922],
       [0.14146111, 0.14801467, 0.51623892]])

In [93]:
arr = np.random.rand(2, 3, 1)

In [94]:
arr

array([[[0.92065326],
        [0.78217956],
        [0.21964365]],

       [[0.26090949],
        [0.63678775],
        [0.52979445]]])

In [95]:
arr.shape

(2, 3, 1)

In [ ]:
np.random.randn()  # standard normal distribution

0.8848792638301952

In [99]:
np.random.randn(3)

array([0.26145086, 1.20109893, 1.39681402])

In [100]:
np.random.randn(3, 5)

array([[-0.59875774, -0.67011637, -0.29368338, -0.53117427,  1.19770502],
       [-0.22777409,  0.26097997, -1.69932416, -1.46380645,  0.12489898],
       [-2.24236563,  1.83156463, -0.35038766, -0.97426155, -0.50396161]])

In [102]:
np.random.randint(5)

4

In [ ]:
np.random.randint(1, 21)  # uniform distribution

16

In [107]:
np.random.randint(10, 26, size=(2, 3))

array([[25, 12, 15],
       [12, 22, 23]])

### Exercise

In [111]:
# 1
customer_ids = np.array([1001, 1002, 1003, 1004, 1005])
customer_ids

array([1001, 1002, 1003, 1004, 1005])

In [112]:
np.array(range(1001, 1006))

array([1001, 1002, 1003, 1004, 1005])

In [135]:
np.arange(1001, 1006)

array([1001, 1002, 1003, 1004, 1005])

In [115]:
# 2
ages = np.arange(25, 46, 5)
ages

array([25, 30, 35, 40, 45])

In [ ]:
# 3
purchase_amounts = np.array(
    [
        [100, 200, 300, 400, 500],
        [150, 250, 350, 450, 550],
        [200, 300, 400, 500, 600],
    ]
)

purchase_amounts

array([[100, 200, 300, 400, 500],
       [150, 250, 350, 450, 550],
       [200, 300, 400, 500, 600]])

In [137]:
np.array(
    [
        range(100, 501, 100),
        range(150, 551, 100),
        range(200, 601, 100),
    ]
)

array([[100, 200, 300, 400, 500],
       [150, 250, 350, 450, 550],
       [200, 300, 400, 500, 600]])

In [ ]:
# 4
sales_data = np.array(
    [
        [[customer_ids[i], ages[i]] for i in range(5)],
        [[customer_ids[i], purchase_amounts[0, i]] for i in range(5)],
        [[customer_ids[i], purchase_amounts[1, i]] for i in range(5)],
        [[customer_ids[i], purchase_amounts[2, i]] for i in range(5)],
    ]
)

sales_data

array([[[1001,   25],
        [1002,   30],
        [1003,   35],
        [1004,   40],
        [1005,   45]],

       [[1001,  100],
        [1002,  200],
        [1003,  300],
        [1004,  400],
        [1005,  500]],

       [[1001,  150],
        [1002,  250],
        [1003,  350],
        [1004,  450],
        [1005,  550]],

       [[1001,  200],
        [1002,  300],
        [1003,  400],
        [1004,  500],
        [1005,  600]]])

In [138]:
sales_data.shape

(4, 5, 2)

In [133]:
# 5
large_sales = purchase_amounts[purchase_amounts > 300]
large_sales

array([400, 500, 350, 450, 550, 400, 500, 600])

In [134]:
# 6
random_purchases = np.random.randint(100, 1001, size=(3, 5))
random_purchases

array([[890, 618, 187, 311, 189],
       [580, 386, 249, 342, 506],
       [513, 513, 122, 665, 952]])