# Coding Practice Session 4
## NumPy Data Types

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4], dtype="i4")

In [3]:
arr

array([1, 2, 3, 4], dtype=int32)

In [4]:
arr.dtype

dtype('int32')

### Numeric Data Types

In [9]:
np.array([500, 350, 879], dtype=np.uint16)

array([500, 350, 879], dtype=uint16)

In [10]:
np.array([-250, 85, -45], dtype="i2")

array([-250,   85,  -45], dtype=int16)

In [12]:
np.array([-1.5, 10.88, 330.56], dtype=np.float16)

array([ -1.5 ,  10.88, 330.5 ], dtype=float16)

In [13]:
np.arange(10, 15, 0.65, dtype="f2")

array([10.   , 10.65 , 11.3  , 11.945, 12.59 , 13.24 , 13.89 , 14.54 ],
      dtype=float16)

In [14]:
np.array([0.5 + 4j, 32 - 10j], dtype=np.complex64)

array([ 0.5 +4.j, 32. -10.j], dtype=complex64)

In [16]:
np.array([11 + 2j, 15 - 12j], dtype="c8")

array([11. +2.j, 15.-12.j], dtype=complex64)

### Boolean Data Types

In [17]:
arr = np.array([True, False, True, True, False])
arr

array([ True, False,  True,  True, False])

In [18]:
arr.dtype

dtype('bool')

In [21]:
np.array([-22, 3, 4, 0, 8], dtype=np.bool)

array([ True,  True,  True, False,  True])

In [22]:
arr = np.array([1, 2, 3, 4, 5])

In [23]:
mask = arr > 3
mask

array([False, False, False,  True,  True])

In [24]:
mask.dtype

dtype('bool')

In [25]:
arr == 2

array([False,  True, False, False, False])

In [26]:
(arr > 2) & (arr <= 4)

array([False, False,  True,  True, False])

In [28]:
arr[arr >= 2.5]

array([3, 4, 5])

In [29]:
arr[mask]

array([4, 5])

In [30]:
arr[mask] = 0
arr

array([1, 2, 3, 0, 0])

### String Data Type

In [31]:
np.array(["Hello", "World"], dtype="S10")

array([b'Hello', b'World'], dtype='|S10')

In [33]:
np.array(["Somethings", "Anyone"], dtype="S4")

array([b'Some', b'Anyo'], dtype='|S4')

In [35]:
np.array(["Hello", "آراد"], dtype="U10")

array(['Hello', 'آراد'], dtype='<U10')

In [42]:
arr = np.array(["apple", "banana", "cherry", "kiwi"])
arr

array(['apple', 'banana', 'cherry', 'kiwi'], dtype='<U6')

In [ ]:
arr == "banana"

array([False,  True, False, False])

In [44]:
arr < "cherry"

array([ True,  True, False, False])

In [45]:
arr1 = np.array(["apple", "ice"])
arr2 = np.array(["pie", "cream"])

In [46]:
np.char.add(arr1, arr2)

array(['applepie', 'icecream'], dtype='<U10')

In [47]:
arr

array(['apple', 'banana', 'cherry', 'kiwi'], dtype='<U6')

In [50]:
np.char.find(arr, "w")

array([-1, -1, -1,  2])

In [51]:
np.char.upper(arr)

array(['APPLE', 'BANANA', 'CHERRY', 'KIWI'], dtype='<U6')

In [52]:
np.char.title(arr)

array(['Apple', 'Banana', 'Cherry', 'Kiwi'], dtype='<U6')

### Object Data Type

In [56]:
arr = np.array([1, 2.5, "Hello", [1, 2], (4, 6)], dtype=np.object_)
arr

array([1, 2.5, 'Hello', list([1, 2]), (4, 6)], dtype=object)

In [57]:
arr[1]

2.5

In [58]:
arr[3]

[1, 2]

In [59]:
arr[2]

'Hello'

### Structured Data Types

In [ ]:
data_types = [("name", "U10"), ("age", "u1"), ("height", "f2")]
arr = np.array([("John", 25, 1.83), ("Mary", 32, 1.65), ("Tim", 7, 1.24)], dtype=data_types)

In [63]:
arr.dtype

dtype([('name', '<U10'), ('age', 'u1'), ('height', '<f2')])

In [64]:
arr["name"]

array(['John', 'Mary', 'Tim'], dtype='<U10')

In [65]:
arr["age"]

array([25, 32,  7], dtype=uint8)

In [66]:
arr[0]

np.void(('John', 25, 1.83), dtype=[('name', '<U10'), ('age', 'u1'), ('height', '<f2')])

In [67]:
print(arr[1])

('Mary', 32, 1.65)


In [69]:
arr[arr["name"] == "John"]

array([('John', 25, 1.83)],
      dtype=[('name', '<U10'), ('age', 'u1'), ('height', '<f2')])

In [70]:
arr[arr["age"] > 18]

array([('John', 25, 1.83), ('Mary', 32, 1.65)],
      dtype=[('name', '<U10'), ('age', 'u1'), ('height', '<f2')])

### Casting Data Types

In [71]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([0.75, 1.86, 2.5])

In [73]:
result = arr_int + arr_float
result

array([1.75, 3.86, 5.5 ])

In [74]:
result.dtype

dtype('float64')

In [75]:
arr_float

array([0.75, 1.86, 2.5 ])

In [76]:
arr_float.astype(np.int16)

array([0, 1, 2], dtype=int16)

In [77]:
arr_float.astype(str)

array(['0.75', '1.86', '2.5'], dtype='<U32')

### Memory Considerations

In [81]:
arr = np.ones((1000, 1000), dtype="f8")
size = arr.nbytes / 1e6
print(f"Size of array (arr) is {size} MB")

Size of array (arr) is 8.0 MB


In [82]:
arr_float64 = np.zeros((1000, 1000), dtype=np.float64)
arr_float32 = np.zeros((1000, 1000), dtype=np.float32)

In [ ]:
arr_float64.nbytes / 1e6 # MB

8.0

In [ ]:
arr_float32.nbytes / 1e6 # MB

4.0

### Exercise

In [85]:
# 1
arr1 = np.array([1, 2, 3, 4, 5], dtype="i4")
arr1

array([1, 2, 3, 4, 5], dtype=int32)

In [87]:
# 2
arr2 = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
arr2

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [88]:
arr2.dtype

dtype('float64')

In [89]:
# 3
result = arr1 + arr2
result

array([ 2.5,  4.5,  6.5,  8.5, 10.5])

In [91]:
print(f"Data type of array (result) is {result.dtype}.")

Data type of array (result) is float64.


In [94]:
# 4
data_types = [("name", "S10"), ("age", "u1"), ("grade", np.float16)]
student = np.array(
    [
        ("John", 18, 85.5),
        ("Alice", 20, 92.0),
        ("Bob", 19, 88.7)
    ], dtype=data_types
)

In [95]:
student

array([(b'John', 18, 85.5), (b'Alice', 20, 92. ), (b'Bob', 19, 88.7)],
      dtype=[('name', 'S10'), ('age', 'u1'), ('grade', '<f2')])

In [105]:
# 5
print(f"Names:", student["name"])

Names: [b'John' b'Alice' b'Bob']


In [106]:
# 6
student["grade"] = student["grade"].astype(int)
student

array([(b'John', 18, 85.), (b'Alice', 20, 92.), (b'Bob', 19, 88.)],
      dtype=[('name', 'S10'), ('age', 'u1'), ('grade', '<f2')])

In [100]:
# 7
mask = arr1 > 3
mask

array([False, False, False,  True,  True])

In [101]:
# 8
arr1[mask]

array([4, 5], dtype=int32)

In [ ]:
# 9
print(f"Size of arr1 in bytes: {arr1.nbytes}")
print(f"Size of arr2 in bytes: {arr2.nbytes}")

Size of arr1 in bytes: 20
Size of arr2 in bytes: 40


In [107]:
# 10
arr3 = np.zeros_like(arr1, dtype="f4")
arr3

array([0., 0., 0., 0., 0.], dtype=float32)