# Coding Practice Session 5
## Broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
scalar = 10

In [3]:
arr + scalar

array([11, 12, 13])

### Rules of broadcasting

#### Rule 1: Matching Dimensions

In [36]:
arr1 = np.random.randint(1, 10, size=3)
arr1  # gets broadcasted to (1, 3)

array([1, 7, 6])

In [37]:
arr1.shape

(3,)

In [38]:
arr2 = np.random.randint(1, 10, size=(4, 3))
arr2

array([[8, 8, 8],
       [4, 9, 1],
       [9, 1, 7],
       [8, 6, 2]])

In [39]:
result = arr2 * arr1
result

array([[ 8, 56, 48],
       [ 4, 63,  6],
       [ 9,  7, 42],
       [ 8, 42, 12]])

In [40]:
result.shape

(4, 3)

In [41]:
arr1 = np.random.randint(1, 10, size=(2, 3, 3))
arr1

array([[[5, 7, 8],
        [3, 4, 3],
        [8, 9, 6]],

       [[2, 2, 4],
        [1, 5, 5],
        [1, 6, 1]]])

In [ ]:
arr2 = np.random.randint(1, 10, size=(3, 3))  # (1, 3, 3)
arr2

array([[4, 8, 9],
       [3, 1, 2],
       [4, 1, 7]])

In [43]:
result = arr1 * arr2
result

array([[[20, 56, 72],
        [ 9,  4,  6],
        [32,  9, 42]],

       [[ 8, 16, 36],
        [ 3,  5, 10],
        [ 4,  6,  7]]])

In [44]:
result.shape

(2, 3, 3)

In [45]:
a = np.random.rand(4, 3)
b = np.random.rand(4)

a * b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

#### Rule 2: Stretching Scalar Values

In [48]:
arr = np.arange(1, 13).reshape(4, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
scalar = 10

In [ ]:
result = arr + scalar
result

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

#### Rule 3: Stretching Arrays with Size 1

In [51]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [52]:
b = np.array([[1], [2], [3]])
b.shape

(3, 1)

In [53]:
result = a * b
result

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Examples of Broadcasting

In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
arr + 1000

array([[1001, 1002, 1003, 1004],
       [1005, 1006, 1007, 1008],
       [1009, 1010, 1011, 1012]])

In [58]:
one_dim_arr = np.array([500, 600, 700, 800])

In [60]:
arr + one_dim_arr

array([[501, 602, 703, 804],
       [505, 606, 707, 808],
       [509, 610, 711, 812]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])

In [62]:
arr1.shape

(2, 3)

In [63]:
arr2.shape

(2, 1)

In [64]:
arr1 + arr2

array([[11, 12, 13],
       [24, 25, 26]])

In [65]:
arr1 / arr2

array([[0.1 , 0.2 , 0.3 ],
       [0.2 , 0.25, 0.3 ]])

In [66]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr2

array([[10],
       [20]])

In [68]:
arr3 = np.array([100, 200, 300])

In [70]:
result = arr1 + arr2 + arr3
result

array([[111, 212, 313],
       [124, 225, 326]])

In [71]:
assert result.shape == (2, 3), f"Expected output shape of (2, 3), got {result.shape}"

**Note:** use `assert` to validate the shape of arrays, to make sure your operations are performing as expected and reach the desired goal.

In [85]:
np.broadcast_shapes((3, 2), (3, 1))

(3, 2)

### Exercise

In [ ]:
# 1
arr1 = np.random.randint(1, 11, size=(3, 4))  # 3x4
arr1

array([[4, 5, 9, 3],
       [9, 6, 5, 9],
       [7, 8, 2, 4]])

In [ ]:
# 2
arr2 = np.array([2, 4, 6, 8])  # 1x4

In [75]:
arr2.shape

(4,)

In [76]:
# 3
result1 = arr1 + arr2
result1

array([[ 6,  9, 15, 11],
       [11, 10, 11, 17],
       [ 9, 12,  8, 12]])

In [ ]:
# 4
arr3 = np.array([[10], [20], [30]]) # 3x1
arr3

array([[10],
       [20],
       [30]])

In [78]:
# 5
result2 = arr1 * arr3
result2

array([[ 40,  50,  90,  30],
       [180, 120, 100, 180],
       [210, 240,  60, 120]])

In [79]:
# 6
scalar = 5

In [80]:
# 7
result3 = result1 - scalar
result3

array([[ 1,  4, 10,  6],
       [ 6,  5,  6, 12],
       [ 4,  7,  3,  7]])

In [83]:
np.broadcast_shapes((5, 2), (2, ))

(5, 2)