# Coding Practice Session 9
## Sorting and Searching

In [1]:
import numpy as np

### 1. Sorting Arrays

In [9]:
arr = np.arange(1, 7)
np.random.shuffle(arr)
arr

array([3, 2, 6, 5, 1, 4])

In [10]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [11]:
arr

array([3, 2, 6, 5, 1, 4])

In [12]:
np.shares_memory(arr, np.sort(arr))

False

In [16]:
arr = np.random.randint(1, 15, size=(2, 3))
np.random.shuffle(arr)
arr

array([[ 8,  9,  1],
       [12,  3,  4]])

In [17]:
np.sort(arr, axis=0)

array([[ 8,  3,  1],
       [12,  9,  4]])

In [18]:
np.sort(arr, axis=1)

array([[ 1,  8,  9],
       [ 3,  4, 12]])

In [19]:
np.sort(arr)

array([[ 1,  8,  9],
       [ 3,  4, 12]])

In [20]:
arr = np.array([3, 1, 5, 2, 4])
arr

array([3, 1, 5, 2, 4])

In [21]:
arr.sort()

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr = np.array([[3, 1, 4], [2, 5, 6]])
arr.sort(axis=0)
arr

array([[2, 1, 4],
       [3, 5, 6]])

In [24]:
arr.sort()
arr

array([[1, 2, 4],
       [3, 5, 6]])

In [31]:
values = [
    ("Arad", 1.83, 23),
    ("Samantha", 1.7, 21),
    ("Christy", 1.8, 45),
]

In [32]:
data_types = [("name", "U15"), ("height", "f2"), ("age", "u1")]

In [33]:
arr = np.array(values, dtype=data_types)
print(arr)

[('Arad', 1.83, 23) ('Samantha', 1.7 , 21) ('Christy', 1.8 , 45)]


In [34]:
type(arr)

numpy.ndarray

In [36]:
print(np.sort(arr, order="height"))

[('Samantha', 1.7 , 21) ('Christy', 1.8 , 45) ('Arad', 1.83, 23)]


In [37]:
np.sort(arr, order="age")

array([('Samantha', 1.7 , 21), ('Arad', 1.83, 23), ('Christy', 1.8 , 45)],
      dtype=[('name', '<U15'), ('height', '<f2'), ('age', 'u1')])

In [40]:
arr = np.arange(20, 26, dtype="u1")
np.random.shuffle(arr)
arr

array([25, 23, 22, 20, 24, 21], dtype=uint8)

In [41]:
np.argsort(arr)

array([3, 5, 2, 1, 4, 0])

In [42]:
arr[np.argsort(arr)]

array([20, 21, 22, 23, 24, 25], dtype=uint8)

In [43]:
arr

array([25, 23, 22, 20, 24, 21], dtype=uint8)

In [84]:
arr = np.arange(40, 46, dtype="u1")
arr

array([40, 41, 42, 43, 44, 45], dtype=uint8)

In [85]:
np.random.shuffle(arr)
arr = arr.reshape(2, 3)
arr

array([[43, 40, 42],
       [45, 44, 41]], dtype=uint8)

In [ ]:
np.argsort(arr)

array([[1, 2, 0],
       [2, 1, 0]])

In [87]:
np.argsort(arr, axis=0)

array([[0, 0, 1],
       [1, 1, 0]])

In [88]:
arr = np.array([3, 1, 4, 2, 5])

In [ ]:
np.sort(arr)[::-1]  # descending order

array([5, 4, 3, 2, 1])

In [ ]:
l = [1, 2, 3, 4, 5]
l_descending = l[::-1]
l_descending

[5, 4, 3, 2, 1]

In [92]:
np.shares_memory(l, l_descending)

False

In [96]:
np.shares_memory(np.sort(arr), np.sort(arr)[::-1])

False

### 2. Searching and Filtering

In [97]:
arr = np.array([1, 2, 3, 4, 5])

In [98]:
5 in arr

True

In [99]:
filtered_arr = arr[arr > 3]
filtered_arr

array([4, 5])

In [100]:
np.shares_memory(arr, filtered_arr)

False

In [ ]:
arr > 3  # creates boolean mask

array([False, False, False,  True,  True])

In [103]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
mask = (arr % 2 == 0) & (arr > 4)
arr[mask]

array([ 6,  8, 10])

In [106]:
arr[(arr % 3 == 0) | (arr % 4 == 0)]

array([3, 4, 6, 8, 9])

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
indices = np.where(arr % 3 == 0)
indices

(array([2, 5, 8]),)

In [111]:
indices = np.where((arr >= 3) & (arr < 8))
indices

(array([2, 3, 4, 5, 6]),)

In [114]:
arr = np.random.randint(-10, 10, size=8)
arr

array([ 4, -8, -5, -4, -2,  7, -3,  9])

In [115]:
result = np.where(arr < 0, 0, arr)
result

array([4, 0, 0, 0, 0, 7, 0, 9])

In [116]:
np.may_share_memory(result, arr)

False

In [117]:
arr

array([ 4, -8, -5, -4, -2,  7, -3,  9])

In [119]:
np.where(abs(arr) >= 5)

(array([1, 2, 5, 7]),)

In [148]:
arr = np.random.randint(5, 15, size=6)
arr

array([ 9,  9, 14,  7, 12, 14])

In [149]:
np.argmax(arr)

np.int64(2)

In [150]:
np.argmin(arr)

np.int64(3)

In [136]:
arr = np.array([2, 2, 3, 4, 4, 5, 3, 5, 5, 3, 1, np.nan, np.nan])
arr

array([ 2.,  2.,  3.,  4.,  4.,  5.,  3.,  5.,  5.,  3.,  1., nan, nan])

In [137]:
np.unique(arr)

array([ 1.,  2.,  3.,  4.,  5., nan])

In [138]:
unique_arr, counts = np.unique(arr, return_counts=True)

In [139]:
unique_arr

array([ 1.,  2.,  3.,  4.,  5., nan])

In [140]:
counts

array([1, 2, 3, 2, 3, 2])

In [141]:
np.unique_values(arr)

array([ 1.,  2.,  3.,  4.,  5., nan, nan])

In [142]:
np.unique_all(arr)

UniqueAllResult(values=array([ 1.,  2.,  3.,  4.,  5., nan, nan]), indices=array([10,  0,  2,  3,  5, 11, 12]), inverse_indices=array([1, 1, 2, 3, 3, 4, 2, 4, 4, 2, 0, 5, 6]), counts=array([1, 2, 3, 2, 3, 1, 1]))

### 3. Set Operations

In [151]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

In [152]:
np.intersect1d(arr1, arr2)

array([4, 5])

In [153]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [154]:
np.setdiff1d(arr1, arr2)

array([1, 2, 3])

In [155]:
np.setdiff1d(arr2, arr1)

array([6, 7, 8])

### Exercise

In [166]:
grades = np.array([85, 72, 90, 68, 77, 82, 92, 60, 55, 75, 88, 80, 95, 78, 65])

In [167]:
grades

array([85, 72, 90, 68, 77, 82, 92, 60, 55, 75, 88, 80, 95, 78, 65])

In [170]:
# 1
sorted_grades = np.sort(grades)
sorted_grades

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])

In [181]:
# 2
top_grades = sorted_grades[-5:]
top_grades

array([85, 88, 90, 92, 95])

In [188]:
# 3
np.count_nonzero(sorted_grades >= 60)

14

In [189]:
np.sum(sorted_grades >= 60)

np.int64(14)

In [185]:
# 4
mean_grade = np.round(np.mean(sorted_grades), 0)
mean_grade

np.float64(77.0)

In [191]:
indices = np.where(grades < mean_grade)
indices

(array([ 1,  3,  7,  8,  9, 14]),)

In [192]:
grades[indices]

array([72, 68, 60, 55, 75, 65])

In [193]:
np.where(sorted_grades < mean_grade)

(array([0, 1, 2, 3, 4, 5]),)

In [194]:
sorted_grades[:6]

array([55, 60, 65, 68, 72, 75])

In [187]:
# 5
np.unique(sorted_grades)

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])