# Coding Practice Session 10
## Saving and Loading NumPy Objects

In [1]:
import numpy as np

### Saving Numpy Arrays as binary files

In [2]:
day_delta = np.random.randint(0, 365, 1_000) * np.timedelta64(1, "D")

In [3]:
# sample array
date_arr = np.datetime64("2025-01-01") + day_delta

In [4]:
date_arr[:5]

array(['2025-10-09', '2025-10-07', '2025-03-14', '2025-04-15',
       '2025-06-03'], dtype='datetime64[D]')

In [5]:
np.save("./data/date_arr.npy", date_arr, allow_pickle=False)

In [6]:
# sample arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 13).reshape(3, 4)

In [7]:
np.savez("./data/sample_arrays.npz", arr1=arr1, arr2=arr2, allow_pickle=False)

In [8]:
# large sample arrays
arr1 = np.random.rand(1000, 1000)
arr2 = np.random.rand(500, 500)

In [9]:
file_path = r"./data/compressed_arrays.npz"
np.savez_compressed(file_path, arr1=arr1, arr2=arr2, allow_pickle=False)

### Loading Numpy Arrays

In [10]:
loaded_date_arr = np.load("./data/date_arr.npy")

In [11]:
loaded_date_arr[:10]

array(['2025-10-09', '2025-10-07', '2025-03-14', '2025-04-15',
       '2025-06-03', '2025-06-12', '2025-09-21', '2025-12-29',
       '2025-07-21', '2025-09-25'], dtype='datetime64[D]')

In [12]:
type(loaded_date_arr)

numpy.ndarray

In [13]:
loaded_date_arr.size

1000

In [14]:
loaded_arrays = np.load("./data/sample_arrays.npz")

In [15]:
loaded_arrays

NpzFile './data/sample_arrays.npz' with keys: arr1, arr2

In [16]:
arr1 = loaded_arrays["arr1"]
arr1

array([1, 2, 3, 4, 5])

In [17]:
arr2 = loaded_arrays["arr2"]
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
loaded_arrays.files

['arr1', 'arr2']

In [19]:
loaded_compressed_arrays = np.load("./data/compressed_arrays.npz")

In [20]:
loaded_compressed_arrays

NpzFile './data/compressed_arrays.npz' with keys: arr1, arr2

In [21]:
compressed_arr1 = loaded_compressed_arrays["arr1"]

In [22]:
compressed_arr1[:5, :5]

array([[0.81447573, 0.59840188, 0.23972272, 0.17693147, 0.20711168],
       [0.10279181, 0.76586664, 0.85690847, 0.18744891, 0.92086124],
       [0.15623133, 0.63147394, 0.58887241, 0.86092141, 0.20608154],
       [0.14593636, 0.39062612, 0.87914499, 0.06543721, 0.85317362],
       [0.41590543, 0.20104726, 0.1212992 , 0.88728246, 0.55026018]])

In [23]:
compressed_arr1.shape

(1000, 1000)

In [24]:
compressed_arr2 = loaded_compressed_arrays["arr2"]

In [25]:
compressed_arr2.shape

(500, 500)

In [26]:
compressed_arr2[:5, :5]

array([[0.52202383, 0.34259423, 0.25619053, 0.41101366, 0.56230277],
       [0.58837553, 0.42527203, 0.60190845, 0.01724134, 0.55357188],
       [0.95910175, 0.32104791, 0.30093557, 0.2080664 , 0.22164483],
       [0.80978442, 0.46489595, 0.85771272, 0.3130908 , 0.50321528],
       [0.40092313, 0.91181427, 0.38105423, 0.69725272, 0.47447963]])

### Saving and Loading Numpy Arrays in Text Format

In [27]:
# sample array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype="u1")

In [28]:
np.savetxt("./data/sample_array.txt", arr, delimiter=",", fmt="%d")

In [29]:
loaded_array = np.loadtxt("./data/sample_array.txt", dtype="u1", delimiter=",")

In [30]:
loaded_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=uint8)

In [31]:
type(loaded_array)

numpy.ndarray

In [32]:
loaded_array.dtype

dtype('uint8')

### Saving and Loading Numpy Arrays in CSV Format

In [33]:
student_ids = np.array([[9823084], [9923114], [9823036]], dtype="u4")
grades = np.array([20, 17.5, 18.0], dtype="f2").reshape(3, 1)

data_arr = np.hstack((student_ids, grades))

In [34]:
data_arr

array([[9.823084e+06, 2.000000e+01],
       [9.923114e+06, 1.750000e+01],
       [9.823036e+06, 1.800000e+01]])

In [35]:
np.savetxt(
    "./data/grades.csv",
    data_arr,
    delimiter=", ",
    header="student id, grade",
    fmt=("%d", "%.2f"),
    comments="",
)

In [36]:
loaded_array = np.genfromtxt("./data/grades.csv", delimiter=", ", skip_header=1)

In [37]:
grades = np.astype(loaded_array[:, 1], "f2")

In [38]:
grades

array([20. , 17.5, 18. ], dtype=float16)

In [39]:
student_ids = np.astype(loaded_array[:, 0], "u4")

In [40]:
student_ids

array([9823084, 9923114, 9823036], dtype=uint32)

In [41]:
data_type = [("Student ID", int), ("Grade", float)]
np.genfromtxt("./data/grades.csv", delimiter=", ", dtype=data_type, skip_header=1)

array([(9823084, 20. ), (9923114, 17.5), (9823036, 18. )],
      dtype=[('Student_ID', '<i8'), ('Grade', '<f8')])

### Exercise

In [42]:
# 1
data = np.arange(1, 10, dtype="u1").reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [43]:
# 2
np.save("./data/array_data.npy", data, allow_pickle=False)

In [ ]:
# 3
loaded_data = np.load("./data/array_data.npy")
loaded_data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [71]:
loaded_data.shape

(3, 3)

In [47]:
# 4
matrix = np.array([[1.5, 2.7, 3.2], [4.1, 5.9, 6.8], [7.3, 8.6, 9.4]], dtype="f2")
matrix

array([[1.5, 2.7, 3.2],
       [4.1, 5.9, 6.8],
       [7.3, 8.6, 9.4]], dtype=float16)

In [48]:
# 5
np.savetxt("./data/matrix_data.txt", matrix, fmt="%.1f", delimiter=",")

In [51]:
# 6
loaded_matrix = np.loadtxt("./data/matrix_data.txt", dtype="f2", delimiter=",")
loaded_matrix

array([[1.5, 2.7, 3.2],
       [4.1, 5.9, 6.8],
       [7.3, 8.6, 9.4]], dtype=float16)

In [72]:
loaded_matrix.shape

(3, 3)

In [ ]:
# 7
data_dict = {"array1": data, "array2": matrix}

In [85]:
# 8
np.savez_compressed("./data/data_archive.npz", **data_dict)

In [86]:
# 9
loaded_dict = np.load("./data/data_archive.npz")

In [87]:
loaded_dict.files

['array1', 'array2']

In [88]:
loaded_dict["array1"]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [89]:
loaded_dict["array2"]

array([[1.5, 2.7, 3.2],
       [4.1, 5.9, 6.8],
       [7.3, 8.6, 9.4]], dtype=float16)

In [90]:
loaded_dict["array1"].shape

(3, 3)

In [91]:
loaded_dict["array2"].shape

(3, 3)

In [92]:
# 10
csv_data = np.array(
    [
        ["Name", "Age", "City"],
        ["Alice", 25, "New York"],
        ["Bob", 30, "London"],
        ["Charlie", 35, "Paris"],
    ]
)

In [93]:
# 11
np.savetxt("./data/data.csv", csv_data, delimiter=", ", fmt="%s")

In [94]:
# 12
loaded_csv_data = np.genfromtxt("./data/data.csv", dtype=str, delimiter=", ")
loaded_csv_data

array([['Name', 'Age', 'City'],
       ['Alice', '25', 'New York'],
       ['Bob', '30', 'London'],
       ['Charlie', '35', 'Paris']], dtype='<U8')

In [95]:
loaded_csv_data.shape

(4, 3)

In [96]:
# 13
txt_data = np.array([[1.2, 3.4, 5.6], [7.8, 9.0, 10.2]], dtype="f2")

In [97]:
# 14
np.savetxt("./data/data.txt", txt_data, delimiter=" ", fmt="%.1f")

In [98]:
# 15
loaded_txt_data = np.loadtxt("./data/data.txt", dtype="f2", delimiter=" ")
loaded_txt_data

array([[ 1.2,  3.4,  5.6],
       [ 7.8,  9. , 10.2]], dtype=float16)

In [99]:
loaded_txt_data.shape

(2, 3)