# NumPy Exercise Session 01

In [1]:
import numpy as np

In [ ]:
# 1
np.empty((3, 4), dtype="u1")  # randomly filled

array([[1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [5]:
np.empty((3, 4), dtype="f2")

array([[-2.705e+00,  5.960e-08,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 1.907e-06,  0.000e+00,  0.000e+00,  0.000e+00]], dtype=float16)

In [6]:
np.empty((3, 4))

array([[2.32229847e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.96717238e+160, 1.71830167e+185,
        7.86064182e-067],
       [8.68847060e-071, 1.09800108e-071, 1.17798889e-047,
        3.31335768e-033]])

In [13]:
# 2
a = np.full((3, 4), fill_value=55, order="C")

In [14]:
a

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [15]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [17]:
# 3
python_list1 = [5, 9, 7, 2, 4, 5, 6]
ndarray_1d = np.array(python_list1, dtype="i2")

In [18]:
ndarray_1d

array([5, 9, 7, 2, 4, 5, 6], dtype=int16)

In [19]:
ndarray_1d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [21]:
# 4
np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype="f2")

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float16)

In [ ]:
# 5
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 7, 7], [9, 8, 10]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  7,  7],
        [ 9,  8, 10]]])

In [23]:
arr.shape

(2, 2, 3)

In [24]:
arr.dtype

dtype('int64')

In [25]:
type(arr)

numpy.ndarray

In [26]:
# 6
np.ones((3, 3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [32]:
# 7
np.info(arr)

class:  ndarray
shape:  (2, 2, 3)
strides:  (48, 24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f20801f9d80
byteorder:  little
byteswap:  False
type: int64


In [34]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [35]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [36]:
np.iinfo(np.uint8)

iinfo(min=0, max=255, dtype=uint8)

In [44]:
# 8
arr1 = np.arange(0, 1000, dtype="u2")
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [49]:
# 9
arr2 = np.arange(-3, 3, dtype="f2")
arr2

array([-3., -2., -1.,  0.,  1.,  2.], dtype=float16)

In [55]:
# 10
arr3 = np.arange(2, 10, 0.1, dtype="f2")
arr3

array([2.   , 2.1  , 2.2  , 2.299, 2.398, 2.498, 2.598, 2.697, 2.797,
       2.896, 2.996, 3.096, 3.195, 3.295, 3.395, 3.494, 3.594, 3.693,
       3.793, 3.893, 3.992, 4.094, 4.19 , 4.29 , 4.39 , 4.492, 4.59 ,
       4.688, 4.79 , 4.89 , 4.99 , 5.086, 5.188, 5.29 , 5.387, 5.484,
       5.586, 5.688, 5.785, 5.883, 5.984, 6.086, 6.184, 6.28 , 6.383,
       6.484, 6.582, 6.68 , 6.78 , 6.883, 6.98 , 7.08 , 7.18 , 7.28 ,
       7.38 , 7.477, 7.58 , 7.68 , 7.777, 7.875, 7.977, 8.08 , 8.17 ,
       8.27 , 8.375, 8.48 , 8.58 , 8.67 , 8.77 , 8.875, 8.97 , 9.07 ,
       9.17 , 9.27 , 9.375, 9.47 , 9.57 , 9.67 , 9.766, 9.87 ],
      dtype=float16)

In [59]:
(10 - 2) / 0.1

80.0

In [61]:
np.linspace(2, 10, num=80, endpoint=False, dtype="f2")

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9], dtype=float16)

### **Note:** When steps are floating point numbers, e.g. 0.1, it's better to use `numpy.linspace`.

In [64]:
# 11
arr4 = np.arange(-0.5, 0.2, 0.1)
arr4

array([-5.00000000e-01, -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
       -1.00000000e-01, -1.11022302e-16,  1.00000000e-01])

In [66]:
# 12
arr5 = np.linspace(-3, 3, num=16, dtype="f2")
arr5

array([-3. , -2.6, -2.2, -1.8, -1.4, -1. , -0.6, -0.2,  0.2,  0.6,  1. ,
        1.4,  1.8,  2.2,  2.6,  3. ], dtype=float16)

In [68]:
# 13
np.eye(4, 4, dtype="i2")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [71]:
np.diag([1, 1, 1, 1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [75]:
np.full(3, 10)

array([10, 10, 10])

In [74]:
np.diag(np.full(3, 10))

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [78]:
# 14
np.eye(5, k=2, dtype="u2")

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint16)

In [80]:
# 15
arr6 = np.diag(np.linspace(1, 121, num=7, dtype="i2"))
arr6

array([[  1,   0,   0,   0,   0,   0,   0],
       [  0,  21,   0,   0,   0,   0,   0],
       [  0,   0,  41,   0,   0,   0,   0],
       [  0,   0,   0,  61,   0,   0,   0],
       [  0,   0,   0,   0,  81,   0,   0],
       [  0,   0,   0,   0,   0, 101,   0],
       [  0,   0,   0,   0,   0,   0, 121]], dtype=int16)

In [81]:
arr6.shape

(7, 7)

In [85]:
# 16
z = np.arange(25, dtype="u1").reshape(5, 5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=uint8)

In [86]:
arr7 = np.diag(z, k=-2)
arr7

array([10, 16, 22], dtype=uint8)

In [88]:
# 17
arr8 = np.zeros((6, 4), dtype="i4")
arr8

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [97]:
# 18
rng = np.random.default_rng(7)

In [98]:
print(rng)

Generator(PCG64)


In [99]:
rng.random()

0.625095466604667

In [102]:
np.random.seed(7)

In [103]:
np.random.random()

0.07630828937395717

In [105]:
# 19
rng.standard_normal(2, dtype="f4")

array([ 1.1501616, -1.7846532], dtype=float32)

In [109]:
rng.integers(-10, 10)

np.int64(-6)

In [113]:
# 20
np.full((6, 3), fill_value=[-np.inf, np.nan, np.inf])

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])