# Numpy Exercise Session 03

In [1]:
import numpy as np

In [3]:
# 1
arr1 = np.array([[5, 6, 9], [21, 18, 27]])
arr1

array([[ 5,  6,  9],
       [21, 18, 27]])

In [5]:
arr2 = np.array([15, 33, 24, 4, 7, 1]).reshape(2, -1)
arr2

array([[15, 33, 24],
       [ 4,  7,  1]])

In [6]:
result_arr = arr1 + arr2
result_arr

array([[20, 39, 33],
       [25, 25, 28]])

In [7]:
result_arr ** 2

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [8]:
np.power(result_arr, 2)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [10]:
# 2
arr = np.arange(start=10, stop=34, step=1).reshape(8, 3)

In [11]:
arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [12]:
np.split(arr, 4, axis=0)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [14]:
np.vsplit(arr, 4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [16]:
np.array_split(arr, 4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [25]:
# 3
arr = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [26]:
np.sort(arr, axis=0)

array([[34, 22, 12],
       [53, 43, 66],
       [82, 94, 73]])

In [28]:
np.argsort(arr[1])

array([2, 1, 0])

In [ ]:
arr[:, np.argsort(arr[1])] # sort by second row

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [ ]:
np.argsort(arr[:, 1]) # sort by second column

array([1, 0, 2])

In [32]:
arr[np.argsort(arr[:, 1])]

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [35]:
# 4
arr.max(axis=0)

array([82, 94, 73])

In [36]:
arr.min(axis=1)

array([34, 12, 53])

In [37]:
# 5
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [43]:
new_col = np.array([10, 10, 10]).reshape(-1, 1)
new_col

array([[10],
       [10],
       [10]])

In [52]:
arr = np.delete(arr, 1, axis=1)
arr

array([[34, 73],
       [82, 12],
       [53, 66]])

In [53]:
np.insert(arr, 1, values=new_col.flatten(), axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])