# Numpy Exercise Session 04

## Basic 

In [1]:
import numpy as np

In [2]:
# 1
print(np.__version__)  # dunder or magic attribute

2.4.2


In [3]:
type(dir(np))

list

In [4]:
dir(np)[0:10]

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__']

In [5]:
# 2
arr1 = np.arange(0, 10, step=1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [8]:
arr1.strides

(8,)

In [9]:
# 3
arr2 = np.full(shape=(3, 3), fill_value=np.True_)
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
np.full(shape=(3, 3), dtype=np.bool, fill_value=True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# 4
arr1[1::2]

array([1, 3, 5, 7, 9])

In [12]:
arr1 % 2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [13]:
arr1[arr1 % 2 == 1]

array([1, 3, 5, 7, 9])

In [14]:
# 5
arr3 = arr1.copy()
arr3[arr3 % 2 == 1] = -1

In [15]:
arr3

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
np.where(arr3 % 2 == 1, -1, arr3)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
# 6
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr4 = arr4.reshape(
    2, -1
)  # -1 means try to figure out the 2nd dimension based on the provided info
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr4.shape

(2, 5)

In [20]:
arr4.ndim

2

In [21]:
# 7
arr5 = np.linspace(0, 1, num=10)

In [22]:
arr5

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
# 8
np.eye(3, dtype="u1")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [24]:
# 9
np.random.seed(7)
arr6 = np.random.randint(low=5, high=50, size=(5, 5))

In [25]:
arr6

array([[ 9, 30,  8, 24, 28],
       [44, 33, 19, 28, 13],
       [30, 47, 31, 13, 44],
       [43,  9, 12, 49,  5],
       [16, 11, 24, 49, 10]])

In [26]:
# 10
arr6.ndim

2

In [27]:
arr6.shape

(5, 5)

In [28]:
arr6.size

25

In [29]:
len(arr6)

5

In [30]:
arr6.dtype

dtype('int64')

## Intermediate

In [31]:
# 1
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

In [32]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.concatenate((a, b), axis=0)  # along the rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
# 2
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [37]:
np.intersect1d(a, b, assume_unique=False)

array([2, 4])

In [38]:
# 3
np.setdiff1d(a, b)

array([1, 3, 5, 6])

In [39]:
# 4
np.where(a == b)[0]  # return array of indices

array([1, 3, 5, 7])

In [40]:
# 5
arr7 = np.random.randint(low=0, high=20, size=15)
arr7

array([16,  0,  2,  9, 14,  6,  4, 14,  9,  3,  3,  8, 19, 16,  1])

In [41]:
arr7[(arr7 > 5) & (arr7 < 10)]

array([9, 6, 9, 8])

In [42]:
# 6
arr8 = np.random.rand(5, 3)
arr8

array([[0.46775286, 0.20484909, 0.49076589],
       [0.37238469, 0.47740115, 0.36589039],
       [0.83791799, 0.76864751, 0.31399468],
       [0.57262533, 0.27604905, 0.45284293],
       [0.35297837, 0.65739946, 0.37035108]])

In [43]:
np.max(arr8, axis=1)

array([0.49076589, 0.47740115, 0.83791799, 0.57262533, 0.65739946])

In [44]:
# 7
def vectorized_max(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    return np.where(x >= y, x, y)

In [45]:
def maxx(x, y):
    return x if x >= y else y

In [46]:
vectorized_maxx = np.vectorize(maxx)

In [47]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [48]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [49]:
vectorized_maxx(a, b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [50]:
vectorized_max(a, b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [51]:
np.maximum(a, b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [52]:
%timeit vectorized_max(a, b)

888 ns ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [53]:
%timeit np.maximum(a, b)

263 ns ± 5.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [54]:
# 8
arr9 = np.arange(9).reshape(3, 3)
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr9[:, [0, 1]] = arr9[:, [1, 0]]

In [56]:
arr9

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [57]:
arr9[:, [1, 0, 2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# 9
arr10 = np.random.randint(10, 20, size=20).reshape(4, -1)

In [59]:
arr10

array([[14, 13, 11, 19, 15],
       [19, 11, 12, 13, 12],
       [12, 15, 17, 13, 10],
       [19, 19, 13, 14, 15]])

In [60]:
arr10[::-1]

array([[19, 19, 13, 14, 15],
       [12, 15, 17, 13, 10],
       [19, 11, 12, 13, 12],
       [14, 13, 11, 19, 15]])

In [61]:
# 10
arr11 = np.random.random(size=(4, 5)) / 1e3
arr11

array([[9.53991406e-04, 1.53739164e-04, 6.49118853e-04, 5.57413528e-04,
        8.68531577e-04],
       [1.43628016e-04, 4.47904347e-04, 6.59233320e-04, 6.61709799e-04,
        8.38566632e-04],
       [5.32557594e-04, 3.96460925e-05, 9.55983530e-05, 7.98894968e-04,
        4.02388484e-04],
       [6.82451951e-04, 5.01923489e-04, 3.97177810e-04, 7.85816693e-04,
        9.51336141e-04]])

In [62]:
with np.printoptions(precision=3, suppress=True):
    print(arr11)

[[0.001 0.    0.001 0.001 0.001]
 [0.    0.    0.001 0.001 0.001]
 [0.001 0.    0.    0.001 0.   ]
 [0.001 0.001 0.    0.001 0.001]]


## Advanced

In [63]:
# 1
a = np.random.randint(low=5, high=20, size=9).reshape(3, 3)
b = np.random.randint(low=-2, high=35, size=3)

In [64]:
a

array([[18, 15,  5],
       [17, 19, 11],
       [ 7, 17, 11]])

In [65]:
b

array([32, 27, 15])

In [66]:
a - b

array([[-14, -12, -10],
       [-15,  -8,  -4],
       [-25, -10,  -4]])

In [67]:
# 2
A = np.random.randint(5, 55, size=15).reshape(5, 3)
B = np.random.randint(5, 65, size=6).reshape(3, 2)

In [68]:
np.matmul(A, B)

array([[2732, 2784],
       [2998, 4248],
       [3686, 4792],
       [1940, 2608],
       [1412, 2538]])

In [69]:
A @ B

array([[2732, 2784],
       [2998, 4248],
       [3686, 4792],
       [1940, 2608],
       [1412, 2538]])

In [70]:
# 3
arr12 = np.random.randint(1, 100, size=9).reshape(3, 3)

In [71]:
arr12

array([[86, 31, 93],
       [57, 52, 56],
       [13, 77, 37]])

In [72]:
result = np.linalg.eig(arr12)
result

EigResult(eigenvalues=array([164.67561941 +0.j        ,   5.16219029+23.73137212j,
         5.16219029-23.73137212j]), eigenvectors=array([[ 0.71262123+0.j        ,  0.67969752+0.j        ,
         0.67969752-0.j        ],
       [ 0.56630301+0.j        ,  0.05241855-0.30062029j,
         0.05241855+0.30062029j],
       [ 0.41409165+0.j        , -0.60828208+0.27364929j,
        -0.60828208-0.27364929j]]))

In [73]:
result.eigenvalues

array([164.67561941 +0.j        ,   5.16219029+23.73137212j,
         5.16219029-23.73137212j])

In [74]:
result.eigenvectors

array([[ 0.71262123+0.j        ,  0.67969752+0.j        ,
         0.67969752-0.j        ],
       [ 0.56630301+0.j        ,  0.05241855-0.30062029j,
         0.05241855+0.30062029j],
       [ 0.41409165+0.j        , -0.60828208+0.27364929j,
        -0.60828208-0.27364929j]])

In [75]:
# 4
A = np.random.randint(0, 100, size=100).reshape(10, 10).astype("f2")

In [76]:
A

array([[71., 85., 58., 41., 15., 43., 59., 82., 63., 28.],
       [16.,  5., 35., 77., 32., 87., 95., 33., 45., 40.],
       [91., 14., 45., 42., 96., 34., 95., 55., 18.,  9.],
       [73., 13., 85., 43.,  1., 31., 14., 80., 48., 25.],
       [33., 85., 83., 82., 64., 77., 58., 10., 52., 27.],
       [28.,  8., 97., 89., 44., 51., 54., 42., 92.,  7.],
       [15.,  0., 82., 48., 64., 44.,  9., 46., 56., 98.],
       [48., 43.,  5., 21., 16., 11., 32., 40., 36., 69.],
       [28., 93., 49., 61., 52., 95.,  7., 92., 58., 50.],
       [48., 78., 47., 62., 77., 83., 77., 24., 67.,  7.]], dtype=float16)

In [77]:
row_indices = np.random.randint(0, A.shape[0], size=5)
col_indices = np.random.randint(0, A.shape[1], size=5)

In [78]:
row_indices

array([1, 0, 1, 4, 6])

In [79]:
col_indices

array([1, 0, 1, 0, 1])

In [80]:
A[row_indices, col_indices] = np.nan

In [81]:
A

array([[nan, 85., 58., 41., 15., 43., 59., 82., 63., 28.],
       [16., nan, 35., 77., 32., 87., 95., 33., 45., 40.],
       [91., 14., 45., 42., 96., 34., 95., 55., 18.,  9.],
       [73., 13., 85., 43.,  1., 31., 14., 80., 48., 25.],
       [nan, 85., 83., 82., 64., 77., 58., 10., 52., 27.],
       [28.,  8., 97., 89., 44., 51., 54., 42., 92.,  7.],
       [15., nan, 82., 48., 64., 44.,  9., 46., 56., 98.],
       [48., 43.,  5., 21., 16., 11., 32., 40., 36., 69.],
       [28., 93., 49., 61., 52., 95.,  7., 92., 58., 50.],
       [48., 78., 47., 62., 77., 83., 77., 24., 67.,  7.]], dtype=float16)

In [82]:
np.isnan(A).sum()

np.int64(4)

In [83]:
A[np.isnan(A)] = np.nanmean(A)

In [84]:
A

array([[50.34, 85.  , 58.  , 41.  , 15.  , 43.  , 59.  , 82.  , 63.  ,
        28.  ],
       [16.  , 50.34, 35.  , 77.  , 32.  , 87.  , 95.  , 33.  , 45.  ,
        40.  ],
       [91.  , 14.  , 45.  , 42.  , 96.  , 34.  , 95.  , 55.  , 18.  ,
         9.  ],
       [73.  , 13.  , 85.  , 43.  ,  1.  , 31.  , 14.  , 80.  , 48.  ,
        25.  ],
       [50.34, 85.  , 83.  , 82.  , 64.  , 77.  , 58.  , 10.  , 52.  ,
        27.  ],
       [28.  ,  8.  , 97.  , 89.  , 44.  , 51.  , 54.  , 42.  , 92.  ,
         7.  ],
       [15.  , 50.34, 82.  , 48.  , 64.  , 44.  ,  9.  , 46.  , 56.  ,
        98.  ],
       [48.  , 43.  ,  5.  , 21.  , 16.  , 11.  , 32.  , 40.  , 36.  ,
        69.  ],
       [28.  , 93.  , 49.  , 61.  , 52.  , 95.  ,  7.  , 92.  , 58.  ,
        50.  ],
       [48.  , 78.  , 47.  , 62.  , 77.  , 83.  , 77.  , 24.  , 67.  ,
         7.  ]], dtype=float16)

In [85]:
np.mean(A)

np.float16(50.34)

In [86]:
A.shape

(10, 10)

In [87]:
np.isnan(A).any()

np.False_

In [88]:
# 6
x = np.random.randint(0, 100, size=25).reshape(5, 5)
x

array([[ 8, 52, 94, 97, 79],
       [22, 56, 53, 34, 12],
       [ 4, 44, 55, 20, 43],
       [49, 18, 56, 21, 50],
       [22, 18, 69,  5,  5]])

In [89]:
x_min = x.min()
x_max = x.max()

In [90]:
x_normalized = (x - x_min) / (x_max - x_min)

In [91]:
x_normalized

array([[0.04301075, 0.51612903, 0.96774194, 1.        , 0.80645161],
       [0.19354839, 0.55913978, 0.52688172, 0.32258065, 0.08602151],
       [0.        , 0.43010753, 0.5483871 , 0.17204301, 0.41935484],
       [0.48387097, 0.15053763, 0.55913978, 0.1827957 , 0.49462366],
       [0.19354839, 0.15053763, 0.69892473, 0.01075269, 0.01075269]])

In [92]:
# 7
def compute_z_score(x: np.ndarray) -> np.ndarray:
    return (x - np.mean(x)) / np.std(x)

In [93]:
np.apply_along_axis(compute_z_score, axis=0, arr=x)

array([[-0.82417259,  0.87467316,  1.86075552,  1.91655878,  1.53228687],
       [ 0.06339789,  1.11763792, -0.80676113, -0.04355815, -0.95953887],
       [-1.07776415,  0.38874362, -0.67663837, -0.47913969,  0.19339543],
       [ 1.77514095, -1.19052735, -0.61157699, -0.44802673,  0.45373543],
       [ 0.06339789, -1.19052735,  0.23422097, -0.9458342 , -1.21987887]])

In [94]:
(x - np.mean(x, axis=0)) / np.std(x, axis=0)

array([[-0.82417259,  0.87467316,  1.86075552,  1.91655878,  1.53228687],
       [ 0.06339789,  1.11763792, -0.80676113, -0.04355815, -0.95953887],
       [-1.07776415,  0.38874362, -0.67663837, -0.47913969,  0.19339543],
       [ 1.77514095, -1.19052735, -0.61157699, -0.44802673,  0.45373543],
       [ 0.06339789, -1.19052735,  0.23422097, -0.9458342 , -1.21987887]])

In [95]:
# 8
y = np.random.normal(size=1000, loc=5, scale=4).round(decimals=0).astype(int)
np.random.choice(y, size=10)

array([0, 5, 9, 7, 8, 6, 6, 8, 0, 3])

In [96]:
np.unique_counts(y)

UniqueCountsResult(values=array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16]), counts=array([  1,   2,   3,   1,   9,  12,  18,  37,  51,  59,  76,  90, 107,
        93,  90,  82,  81,  69,  50,  32,  16,  12,   5,   2,   2]))

In [97]:
values, counts = np.unique_counts(y)

In [98]:
np.asarray((values, counts)).T

array([[ -8,   1],
       [ -7,   2],
       [ -6,   3],
       [ -5,   1],
       [ -4,   9],
       [ -3,  12],
       [ -2,  18],
       [ -1,  37],
       [  0,  51],
       [  1,  59],
       [  2,  76],
       [  3,  90],
       [  4, 107],
       [  5,  93],
       [  6,  90],
       [  7,  82],
       [  8,  81],
       [  9,  69],
       [ 10,  50],
       [ 11,  32],
       [ 12,  16],
       [ 13,  12],
       [ 14,   5],
       [ 15,   2],
       [ 16,   2]])

In [99]:
np.unique(y)

array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16])

In [100]:
# 9
q = np.arange(1, 10, dtype="u1").reshape(3, 3)
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [101]:
q.strides

(3, 1)

In [ ]:
q.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [103]:
# 10
arr = np.random.randint(1, 100, size=20)

In [104]:
def rolling_mean(arr: np.ndarray, window_size: int = 3) -> np.ndarray:
    window = np.ones(shape=window_size) / window_size
    return np.convolve(arr, window, mode="valid")

In [105]:
rolling_mean(arr, 5)

array([36.6, 44.6, 27.2, 36.6, 27. , 31.6, 24.4, 24.2, 20. , 25.4, 31. ,
       48. , 58.4, 68.6, 68.2, 70.4])

In [106]:
result = rolling_mean(np.arange(1, 11))

In [107]:
result

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [108]:
len(result)

8

In [109]:
# 11
a = np.arange(6)
b = a[2:4]

In [110]:
a

array([0, 1, 2, 3, 4, 5])

In [111]:
b

array([2, 3])

In [ ]:
a.base # base is none, means it's original

In [ ]:
b.base # points to the base of b, which is a

array([0, 1, 2, 3, 4, 5])

In [114]:
np.shares_memory(a, b)

True

In [115]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [116]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False