# Numpy Exercise Session 02

In [1]:
import numpy as np

In [6]:
# 1
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.asarray(x, dtype="u1")
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [7]:
np.max(arr, axis=1)

array([3, 6, 9], dtype=uint8)

In [8]:
arr.max()

np.uint8(9)

In [9]:
# 2
arr = np.empty((4, 2), dtype="u2")
arr

array([[    0,     0],
       [    0, 49152],
       [32767, 46251],
       [22033, 37764]], dtype=uint16)

In [10]:
arr.shape

(4, 2)

In [14]:
arr.ndim

2

In [16]:
arr.itemsize # in bytes

2

In [17]:
arr.strides

(4, 2)

In [23]:
np.info(arr)

class:  ndarray
shape:  (4, 2)
strides:  (4, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x62f0fa0
byteorder:  little
byteswap:  False
type: uint16


In [25]:
# 3
arr = np.arange(100, 200, 10, dtype="u2").reshape((5, 2))
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]], dtype=uint16)

In [26]:
arr.shape

(5, 2)

In [27]:
arr.size

10

In [35]:
# 4
arr = np.arange(11, 100, 11, dtype="u1").reshape((3, -1))
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]], dtype=uint8)

In [36]:
arr[:, 2]

array([33, 66, 99], dtype=uint8)

In [43]:
# 5
arr = np.arange(3, 61, 3, dtype="u1").reshape(-1,4)
arr

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]], dtype=uint8)

In [45]:
new_arr = arr[1::2, 0::2]
new_arr

array([[15, 21],
       [39, 45]], dtype=uint8)

In [46]:
np.shares_memory(arr, new_arr)

True