# Coding Practice Session 1
## Introduction to Numpy

In [12]:
import numpy as np
import time

In [5]:
np.__version__

'2.2.4'

In [7]:
arr = np.array([1, 2, 3, 4])

In [10]:
arr

array([1, 2, 3, 4])

In [11]:
type(arr)

numpy.ndarray

In [15]:
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.perf_counter()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.perf_counter()
delta_time = end_time - start_time
print(f"Python list addition time: {delta_time:.3f} seconds")

Python list addition time: 0.076 seconds


In [16]:
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_time = time.perf_counter()
result_arr = arr1 + arr2
end_time = time.perf_counter()
delta_time = end_time - start_time
print(f"Numpy array addition time: {delta_time:.3f} seconds")

Numpy array addition time: 0.016 seconds


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
squared_arr = np.square(arr)
squared_arr

array([ 1,  4,  9, 16, 25])

In [24]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3, 4], [9, 8, 7, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[1, 3], [0, 0]]])

In [25]:
arr_1d

array([1, 2, 3, 4, 5])

In [26]:
arr_2d

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [27]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 3],
        [0, 0]]])

In [28]:
arr_3d.shape

(3, 2, 2)

In [29]:
arr_2d.size

8

In [31]:
print(arr_1d.dtype)

int64


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 11, 12])

arr1 + arr2

array([11, 13, 15])

In [33]:
arr = np.array([[1, 2, 3], [4, 8, 10]])
arr + 100

array([[101, 102, 103],
       [104, 108, 110]])

In [34]:
np.random.rand(5, 2)

array([[0.26688513, 0.40921612],
       [0.00429803, 0.42630498],
       [0.54128539, 0.62763517],
       [0.10574952, 0.96258679],
       [0.59542906, 0.31558968]])

In [35]:
np.random.randint(5, 15)

13

In [40]:
np.zeros(shape=(4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.arange(0, 12, 0.6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4,  6. ,
        6.6,  7.2,  7.8,  8.4,  9. ,  9.6, 10.2, 10.8, 11.4])