# Coding Practice Session 3
## Indexing and Slicing Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [6]:
print(arr[0])

10


In [7]:
arr[1]

np.int64(20)

In [11]:
print(arr[2])

30


In [13]:
arr2 = arr[0] + arr[2]

In [14]:
arr2

np.int64(40)

In [15]:
type(arr2)

numpy.int64

In [17]:
arr2.size

1

In [19]:
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr[1:4]

array([20, 30, 40])

In [20]:
arr[:2]

array([10, 20])

In [21]:
arr[3:]

array([40, 50])

In [23]:
arr[1::2]

array([20, 40])

### Indexing Numpy Arrays

In [25]:
arr = np.arange(10, 61, 10)
arr

array([10, 20, 30, 40, 50, 60])

In [26]:
arr[0]

np.int64(10)

In [27]:
print(arr[0])

10


In [28]:
arr[2]

np.int64(30)

In [29]:
index = 4
arr[index]

np.int64(50)

In [34]:
arr_2d = np.arange(36).reshape((6, 6))
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
arr_2d[0, 2]

np.int64(2)

In [38]:
arr_2d[0][2]

np.int64(2)

In [39]:
print(arr_2d[1, -1])

11


In [40]:
print(arr_2d[-2, 4])

28


In [41]:
arr_2d[-1, -1]

np.int64(35)

In [42]:
arr

array([10, 20, 30, 40, 50, 60])

In [43]:
arr[-2]

np.int64(50)

### Slicing Numpy Arrays

In [44]:
arr = np.array([10, 20, 30, 40, 50])

In [46]:
arr[1:4]

array([20, 30, 40])

In [47]:
arr[:3]

array([10, 20, 30])

In [48]:
arr[2:]

array([30, 40, 50])

In [53]:
arr[-3:-1]

array([30, 40])

In [54]:
arr[-3::-1]

array([30, 20, 10])

In [55]:
arr[::-1]

array([50, 40, 30, 20, 10])

In [56]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
arr_2d[:2, :2] # first two rows, first two columns

array([[0, 1],
       [6, 7]])

In [58]:
arr_2d[:, 1]

array([ 1,  7, 13, 19, 25, 31])

In [59]:
arr_2d[::2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [62]:
arr_2d[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [63]:
arr_2d[::2, ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [64]:
arr_2d[::-1, ::-1]

array([[35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

### Advanced Indexing

In [65]:
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, False, True, True])
arr[mask]

array([1, 4, 5])

In [ ]:
arr >= 3 

array([False, False,  True,  True,  True])

In [71]:
arr[arr >= 3]

array([3, 4, 5])

In [69]:
arr[[True, False, True, True, False]]

array([1, 3, 4])

In [73]:
arr = np.arange(10, 61, 10)
arr

array([10, 20, 30, 40, 50, 60])

In [74]:
indices = np.array([1, 4, 5])
arr[indices]

array([20, 50, 60])

In [76]:
arr_2d = np.arange(1, 10).reshape((3, 3))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
row_indices = [0, 2, 1]
col_indices = [-1, 0, 1]
arr_2d[row_indices, col_indices]

array([3, 7, 5])

In [79]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr_2d[1:, [0, -1]]

array([[4, 6],
       [7, 9]])

In [82]:
arr_2d[1:, [0, 2]]

array([[4, 6],
       [7, 9]])

In [85]:
arr_2d[arr_2d[:, 1] > 3, 1:]

array([[5, 6],
       [8, 9]])

In [86]:
arr_2d[:, 1] > 3

array([False,  True,  True])

### Modifying Arrays Using Indexing and Slicing

In [87]:
arr = np.array([1, 2, 3, 4, 5])

In [90]:
arr[2] = 8
arr

array([1, 2, 8, 4, 5])

In [91]:
arr[[0, 1, -1]] = -10
arr

array([-10, -10,   8,   4, -10])

In [94]:
arr[1:4] = [20, 30, 50]
arr

array([-10,  20,  30,  50, -10])

In [95]:
arr[arr < 0] = 0
arr

array([ 0, 20, 30, 50,  0])

### Views vs. Copies in Slicing

In [97]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
view = arr[1:6]
view

array([2, 3, 4, 5, 6])

In [100]:
view[0] = -100

In [101]:
view

array([-100,    3,    4,    5,    6])

In [102]:
arr

array([   1, -100,    3,    4,    5,    6,    7,    8,    9,   10])

In [103]:
arr[2] = +100

In [104]:
arr

array([   1, -100,  100,    4,    5,    6,    7,    8,    9,   10])

In [105]:
view

array([-100,  100,    4,    5,    6])

In [135]:
arr = np.array([1, 2, 3, 4, 5])

In [136]:
copy_arr = arr[1:4].copy()
copy_arr

array([2, 3, 4])

In [137]:
copy_arr[0] = 100
copy_arr

array([100,   3,   4])

In [138]:
arr

array([1, 2, 3, 4, 5])

In [139]:
a = np.array([1, 2, 3, 4, 5])
b = a[2:4]
c = a.copy()

In [140]:
np.may_share_memory(a, b)

True

In [141]:
np.shares_memory(a, b)

True

In [142]:
np.may_share_memory(a, c)

False

In [143]:
np.may_share_memory(b, c)

False

In [ ]:
print(c.base) # base is None, means it's a copy.

None


In [ ]:
print(b.base) # base is not None, means it's a view.

[1 2 3 4 5]


`b` is a view of `a` so they share memory. `c` is a copy of `a`, so they don't share any memory.

In [155]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [156]:
x = a[a >= 3]
x

array([3, 4, 5])

In [157]:
np.shares_memory(a, x)

False

In [158]:
print(x.base)

None


In [167]:
y = a[np.array([0, -1, 3])]
y

array([1, 5, 4])

In [168]:
np.may_share_memory(a, y)

False

In [ ]:
print(y.base)

None


In [170]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
subset = arr[1:, 1:]
subset ** 2

array([[25, 36],
       [64, 81]])

In [172]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise

In [ ]:
temperatures = np.array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
                         [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
                         [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                          25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
                         [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                          26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
                         [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                          27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
                         [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17],
                         [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                          29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18]])

In [180]:
temperatures.shape

(7, 24)

In [193]:
# 1
print("Temperature readings of the first day:")
print(temperatures[0])

Temperature readings of the first day:
[12 14 15 16 17 18 19 20 21 22 23 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [194]:
# 2
print("Temperature readings of the last day:")
print(temperatures[-1])

Temperature readings of the last day:
[18 20 21 22 23 24 25 26 27 28 29 30 29 28 27 26 25 24 23 22 21 20 19 18]


In [183]:
# 3
temperatures[:, 0:12]

array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [184]:
# 4
temperatures[:, -6:]

array([[17, 16, 15, 14, 13, 12],
       [18, 17, 16, 15, 14, 13],
       [19, 18, 17, 16, 15, 14],
       [20, 19, 18, 17, 16, 15],
       [21, 20, 19, 18, 17, 16],
       [22, 21, 20, 19, 18, 17],
       [23, 22, 21, 20, 19, 18]])

In [186]:
# 5
temperatures[3, ::2]

array([15, 18, 20, 22, 24, 26, 26, 24, 22, 20, 18, 16])

In [187]:
# 6
temperatures[4, 0:3] += 10

In [189]:
temperatures[4]

array([26, 28, 29, 20, 21, 22, 23, 24, 25, 26, 27, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16])

In [191]:
# 7
mask = temperatures > 25
mask

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False, False,
         True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False,

In [192]:
temperatures[mask]

array([26, 26, 27, 26, 26, 28, 29, 26, 27, 28, 27, 26, 26, 27, 28, 29, 28,
       27, 26, 26, 27, 28, 29, 30, 29, 28, 27, 26])

In [201]:
np.shares_memory(temperatures, temperatures[mask])

False

In [202]:
np.shares_memory(temperatures, temperatures[3, ::2])

True