# Coding Practice Session 7
## Mathematical Operations with Numpy

In [1]:
import numpy as np

#### 1. Element-wise Operations

In [2]:
a = np.array([5, 9, 3])
b = np.array([2, 14, 10])

In [3]:
a + b

array([ 7, 23, 13])

In [4]:
np.add(a, b, dtype="i1")

array([ 7, 23, 13], dtype=int8)

In [5]:
a - b

array([ 3, -5, -7])

In [6]:
np.subtract(a, b)

array([ 3, -5, -7])

In [7]:
a * b

array([ 10, 126,  30])

In [8]:
np.multiply(a, b)

array([ 10, 126,  30])

In [9]:
help(np.multiply)

Help on ufunc in module numpy:

multiply = <ufunc 'multiply'>
    multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Multiply arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays to be multiplied.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
  

In [10]:
a = np.array([10, 20, 30])
b = np.array([2, 5, 10])

In [11]:
a / b

array([5., 4., 3.])

In [12]:
a // b

array([5, 4, 3])

In [13]:
np.divide(a, b)

array([5., 4., 3.])

In [14]:
(a / b).dtype

dtype('float64')

### 2. Basic Mathematical Functions

In [15]:
a = np.array([0, np.pi / 6, np.pi / 3, np.pi / 2])

In [16]:
np.sin(a)

array([0.       , 0.5      , 0.8660254, 1.       ])

In [17]:
np.cos(a)

array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17])

In [18]:
np.tan(a)

array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])

In [19]:
np.tan(np.pi / 4, dtype="f4")

np.float32(1.0)

In [20]:
np.arcsin(0.5, dtype="f4")

np.float32(0.5235988)

In [21]:
np.pi / 6

0.5235987755982988

In [22]:
np.arccos(-1)

np.float64(3.141592653589793)

In [23]:
print(np.arctan(1))

0.7853981633974483


In [24]:
np.pi / 4

0.7853981633974483

In [25]:
a = np.array([1, 2, 3])

In [26]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
result = np.exp(complex(0, np.pi), dtype="c8")
result

np.complex64(-1-8.742278e-08j)

In [28]:
np.round(result, 2)

np.complex64(-1-0j)

In [29]:
print(result.real)

-1.0


In [30]:
np.e

2.718281828459045

In [31]:
np.log(np.e)  # natural logarithm (log base e or ln)

np.float64(1.0)

In [32]:
np.log10(1e4)

np.float64(4.0)

In [33]:
np.log2(1)

np.float64(0.0)

In [34]:
np.log2(8)

np.float64(3.0)

In [35]:
np.log10(5)

np.float64(0.6989700043360189)

In [36]:
np.log10(2) + np.log10(5)

np.float64(1.0)

In [37]:
a = np.array([1.254, 4.786, 9.51], dtype="f2")

In [38]:
np.round(a, 1)

array([1.3, 4.8, 9.5], dtype=float16)

In [39]:
np.ceil(a)

array([ 2.,  5., 10.], dtype=float16)

In [40]:
np.floor(a)

array([1., 4., 9.], dtype=float16)

In [41]:
np.ceil(2)

np.int64(2)

In [42]:
np.floor(2)

np.int64(2)

### 3. Aggregation Functions

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
np.sum(a)

np.int64(21)

In [45]:
a.shape

(2, 3)

In [46]:
np.sum(a, axis=0)  # sum of elements in each column

array([5, 7, 9])

In [47]:
np.sum(a, axis=1)  # sum of elements in each row

array([ 6, 15])

In [48]:
arr = np.random.randint(1, 10, size=(2, 3, 4))
arr

array([[[3, 5, 1, 1],
        [1, 6, 5, 7],
        [1, 8, 5, 7]],

       [[9, 1, 8, 9],
        [3, 1, 9, 6],
        [6, 3, 6, 3]]])

In [49]:
arr.shape

(2, 3, 4)

In [50]:
np.sum(arr)

np.int64(114)

In [51]:
np.sum(arr, axis=0)  # sum of elements along the z-axis

array([[12,  6,  9, 10],
       [ 4,  7, 14, 13],
       [ 7, 11, 11, 10]])

In [52]:
np.sum(arr, axis=1)  # sum of elements along the y-axis

array([[ 5, 19, 11, 15],
       [18,  5, 23, 18]])

In [53]:
np.sum(arr, axis=2)  # sum of elements along the x-axis

array([[10, 19, 21],
       [27, 19, 18]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.mean(a)

np.float64(3.5)

In [56]:
np.mean(a, axis=1)  # mean of elements in each row

array([2., 5.])

In [57]:
np.mean(a, axis=0)  # mean of elements in each column

array([2.5, 3.5, 4.5])

In [58]:
arr

array([[[3, 5, 1, 1],
        [1, 6, 5, 7],
        [1, 8, 5, 7]],

       [[9, 1, 8, 9],
        [3, 1, 9, 6],
        [6, 3, 6, 3]]])

In [59]:
np.min(arr)

np.int64(1)

In [60]:
np.min(arr, axis=0)

array([[3, 1, 1, 1],
       [1, 1, 5, 6],
       [1, 3, 5, 3]])

In [61]:
np.min(arr, axis=2)

array([[1, 1, 1],
       [1, 1, 3]])

In [62]:
np.max(arr)

np.int64(9)

In [63]:
np.max(arr, axis=1)

array([[3, 8, 5, 7],
       [9, 3, 9, 9]])

In [64]:
arr = np.random.randint(1, 10, (4, 5))
arr

array([[8, 8, 7, 8, 4],
       [1, 1, 5, 3, 9],
       [1, 6, 2, 8, 2],
       [5, 7, 8, 6, 2]])

In [65]:
np.std(arr)

np.float64(2.747271373563231)

In [66]:
np.var(arr)

np.float64(7.547500000000001)

In [67]:
2.9342801502242417**2

8.609999999999998

In [68]:
np.std(arr, axis=0)

array([2.94745653, 2.6925824 , 2.29128785, 2.04633819, 2.86138079])

In [69]:
np.var(arr, axis=1)

array([2.4 , 8.96, 7.36, 4.24])

In [70]:
arr

array([[8, 8, 7, 8, 4],
       [1, 1, 5, 3, 9],
       [1, 6, 2, 8, 2],
       [5, 7, 8, 6, 2]])

In [71]:
np.median(arr, axis=0)

array([3. , 6.5, 6. , 7. , 3. ])

In [72]:
np.percentile(arr, 85)

np.float64(8.0)

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.prod(a)

np.int64(720)

In [75]:
np.prod(a, axis=0)

array([ 4, 10, 18])

### 4. Matrix Operations

In [76]:
A = np.arange(1, 7).reshape((2, 3))
B = np.arange(5, 11).reshape((3, 2))

In [77]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
B

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:
np.dot(A, B)

array([[ 46,  52],
       [109, 124]])

In [80]:
A @ B

array([[ 46,  52],
       [109, 124]])

In [81]:
A @ B == np.dot(A, B)

array([[ True,  True],
       [ True,  True]])

In [82]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
A = np.random.randint(1, 10, size=(3, 3))
A

array([[7, 6, 6],
       [9, 5, 2],
       [1, 8, 5]])

In [86]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.04347826,  0.08695652, -0.08695652],
       [-0.20772947,  0.14009662,  0.19323671],
       [ 0.3236715 , -0.24154589, -0.09178744]])

In [87]:
np.linalg.det(A)

np.float64(207.0000000000001)

In [88]:
A @ A_inv  # equals identity matrix

array([[ 1.00000000e+00,  5.55111512e-17,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16, -1.38777878e-16,  1.00000000e+00]])

In [89]:
B = np.array([[4, 2], [10, 5]])
np.linalg.inv(B)

array([[ 4.50359963e+15, -1.80143985e+15],
       [-9.00719925e+15,  3.60287970e+15]])

In [90]:
np.linalg.det(B)

np.float64(1.1102230246251546e-15)

### 5. Random Number Generation

In [99]:
np.random.rand(4, 1)

array([[0.36153845],
       [0.27540093],
       [0.53000022],
       [0.30591892]])

In [100]:
np.random.randint(1e3, 1e5)

3065

In [101]:
np.random.randn(2)  # standard normal distribution

array([-0.90211904,  0.68914456])

In [102]:
# normal distribution with specific mean (loc), std (scale)
np.random.normal(loc=5, scale=2, size=3)

array([11.04081307,  5.23948569,  4.91293399])

In [ ]:
np.random.uniform(10, 20)  # uniform distribution between low and high

18.33544091636263

In [104]:
np.random.rand()

0.7059166434906898

In [105]:
np.random.seed(15)

In [106]:
np.random.rand(3)

array([0.8488177 , 0.17889592, 0.05436321])

In [107]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.random.shuffle(arr)
arr

array([5, 4, 2, 8, 6, 9, 1, 3, 7])

In [116]:
np.random.choice(arr, 4, replace=False)

array([1, 9, 7, 3])

### 6. Comparison and Logical Operations

In [123]:
a = np.random.randint(1, 10, size=5)
a

array([9, 7, 4, 3, 8])

In [124]:
b = np.random.randint(1, 10, size=5)
b

array([5, 3, 3, 4, 4])

In [125]:
a == b

array([False, False, False, False, False])

In [128]:
not all(a == b)

True

In [129]:
a != b

array([ True,  True,  True,  True,  True])

In [130]:
a < b

array([False, False, False,  True, False])

In [131]:
a > b

array([ True,  True,  True, False,  True])

In [132]:
a <= b

array([False, False, False,  True, False])

In [133]:
a = np.random.choice([True, False], size=4)
b = np.random.choice([True, False], size=4)

In [134]:
a

array([ True, False, False,  True])

In [135]:
b

array([False, False,  True, False])

In [136]:
a & b

array([False, False, False, False])

In [137]:
a | b

array([ True, False,  True,  True])

In [140]:
~a

array([False,  True,  True, False])

In [142]:
np.not_equal(a, b)

array([ True, False,  True,  True])

In [ ]:
a ^ b  # xor

array([ True, False,  True,  True])

In [144]:
np.greater([2, 5], [8, 2])

array([False,  True])

In [145]:
np.logical_and(a, b)

array([False, False, False, False])

In [146]:
np.logical_or(a, b)

array([ True, False,  True,  True])

In [147]:
np.logical_xor(a, b)

array([ True, False,  True,  True])

### Exercise

In [148]:
temperatures = np.array([25.5, 28.2, 26.8, 29.1, 27.6, 24.9, 26.3])
precipitation = np.array([0.0, 2.5, 0.0, 0.0, 10.2, 5.8, 1.2])

In [ ]:
# 1
fahrenheit_temperatures = (temperatures * 9 / 5) + 32
fahrenheit_temperatures

array([77.9 , 82.76, 80.24, 84.38, 81.68, 76.82, 79.34])

In [155]:
# 2
average_temperature = np.mean(temperatures)
average_precipitation = np.mean(precipitation)
print(f"Average temperature this week: {average_temperature:.0f}")
print(f"Average precipitation this week: {average_precipitation:.2f}")

Average temperature this week: 27
Average precipitation this week: 2.81


In [ ]:
# 3
highest_temp_indx = np.argmax(temperatures)
lowest_precipitation_indx = np.argmin(precipitation)

print(f"Day with the highest temperature: {highest_temp_indx + 1}")
print(f"Day with lowest precipitation: {lowest_precipitation_indx + 1}")

Day with the highest temperature: 4
Day with lowest precipitation: 1


In [ ]:
# 4
# rainy_days = len(precipitation[precipitation > 0])
# or
rainy_days = np.sum(precipitation > 0)
print(f"Number of rainy days: {rainy_days}")

Number of rainy days: 4


In [162]:
# 5
kelvin_temperatures = temperatures[precipitation > 5] + 273.15
kelvin_temperatures

array([300.75, 298.05])

In [161]:
np.where(precipitation > 5, temperatures + 273.15, np.nan)

array([   nan,    nan,    nan,    nan, 300.75, 298.05,    nan])