# Coding Practice Session 8
## Array Manipulation

In [1]:
import numpy as np

### 1. Reshaping Arrays

In [7]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
arr.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
arr_2d = np.arange(1, 7).reshape(2, 3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr.reshape(3, 2)

In [16]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr_2d[0, 0] = 100
arr_2d

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [18]:
arr

array([100,   2,   3,   4,   5,   6])

In [19]:
np.shares_memory(arr, arr.reshape(3, 2))

True

In [ ]:
arr = np.linspace(1, 10, 16)

In [21]:
arr

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6,  5.2,  5.8,  6.4,  7. ,
        7.6,  8.2,  8.8,  9.4, 10. ])

In [22]:
arr.reshape((-1, 4, 2))

array([[[ 1. ,  1.6],
        [ 2.2,  2.8],
        [ 3.4,  4. ],
        [ 4.6,  5.2]],

       [[ 5.8,  6.4],
        [ 7. ,  7.6],
        [ 8.2,  8.8],
        [ 9.4, 10. ]]])

In [25]:
np.linspace(0, 20, 50, dtype="f2").reshape(2, 5, 5)

array([[[ 0.    ,  0.4082,  0.8164,  1.225 ,  1.633 ],
        [ 2.041 ,  2.45  ,  2.857 ,  3.266 ,  3.674 ],
        [ 4.082 ,  4.49  ,  4.9   ,  5.305 ,  5.715 ],
        [ 6.12  ,  6.53  ,  6.938 ,  7.348 ,  7.754 ],
        [ 8.164 ,  8.57  ,  8.98  ,  9.39  ,  9.8   ]],

       [[10.2   , 10.61  , 11.02  , 11.43  , 11.836 ],
        [12.24  , 12.66  , 13.06  , 13.47  , 13.875 ],
        [14.29  , 14.695 , 15.1   , 15.51  , 15.92  ],
        [16.33  , 16.73  , 17.14  , 17.55  , 17.95  ],
        [18.38  , 18.78  , 19.19  , 19.6   , 20.    ]]], dtype=float16)

### 2. Flattening Arrays

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype="i1")

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [ ]:
np.ravel(arr, order="F") # view of original array

array([1, 4, 2, 5, 3, 6], dtype=int8)

In [31]:
np.shares_memory(arr, np.ravel(arr))

True

In [32]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [ ]:
flattened_arr = arr.flatten("F") # copy of original array
flattened_arr

array([1, 4, 2, 5, 3, 6], dtype=int8)

In [36]:
flattened_arr[0] = 100
flattened_arr

array([100,   4,   2,   5,   3,   6], dtype=int8)

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

### 3. Stacking Arrays

In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [42]:
stacked_arr = np.vstack((arr1, arr2))
stacked_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.shape(stacked_arr)

(2, 3)

In [45]:
arr1 = np.arange(1, 5).reshape(2, 2)
arr1

array([[1, 2],
       [3, 4]])

In [48]:
arr2 = np.arange(5, 9).reshape(2, -1)
arr2

array([[5, 6],
       [7, 8]])

In [49]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [53]:
np.hstack((arr2, arr1))

array([4, 5, 6, 1, 2, 3])

In [54]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [55]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [99]:
arr1 = np.arange(1, 21).reshape((2, 2, 5))
arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [100]:
arr2 = np.random.randint(1, 9, size=(2, 2, 5))
arr2

array([[[7, 6, 5, 1, 2],
        [7, 5, 3, 8, 2]],

       [[4, 8, 6, 7, 7],
        [3, 5, 1, 2, 2]]])

In [101]:
np.vstack((arr1, arr2))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[ 7,  6,  5,  1,  2],
        [ 7,  5,  3,  8,  2]],

       [[ 4,  8,  6,  7,  7],
        [ 3,  5,  1,  2,  2]]])

In [102]:
np.hstack((arr1, arr2))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 7,  6,  5,  1,  2],
        [ 7,  5,  3,  8,  2]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [ 4,  8,  6,  7,  7],
        [ 3,  5,  1,  2,  2]]])

In [103]:
np.dstack((arr1, arr2))

array([[[ 1,  2,  3,  4,  5,  7,  6,  5,  1,  2],
        [ 6,  7,  8,  9, 10,  7,  5,  3,  8,  2]],

       [[11, 12, 13, 14, 15,  4,  8,  6,  7,  7],
        [16, 17, 18, 19, 20,  3,  5,  1,  2,  2]]])

### 4. Concatenating Arrays

In [105]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [106]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [107]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [108]:
arr1 = np.random.randint(1, 5, size=(2, 3, 4))
arr1

array([[[2, 2, 2, 3],
        [3, 3, 3, 4],
        [1, 4, 2, 4]],

       [[4, 1, 3, 1],
        [1, 4, 4, 3],
        [1, 1, 2, 2]]])

In [109]:
arr2 = np.random.randint(5, 10, size=(2, 3, 4))
arr2

array([[[7, 6, 5, 8],
        [9, 5, 7, 9],
        [9, 8, 5, 8]],

       [[9, 5, 6, 8],
        [5, 6, 7, 7],
        [7, 9, 7, 9]]])

In [110]:
np.concatenate((arr1, arr2), axis=1)

array([[[2, 2, 2, 3],
        [3, 3, 3, 4],
        [1, 4, 2, 4],
        [7, 6, 5, 8],
        [9, 5, 7, 9],
        [9, 8, 5, 8]],

       [[4, 1, 3, 1],
        [1, 4, 4, 3],
        [1, 1, 2, 2],
        [9, 5, 6, 8],
        [5, 6, 7, 7],
        [7, 9, 7, 9]]])

In [111]:
np.concatenate((arr1, arr2), axis=0)

array([[[2, 2, 2, 3],
        [3, 3, 3, 4],
        [1, 4, 2, 4]],

       [[4, 1, 3, 1],
        [1, 4, 4, 3],
        [1, 1, 2, 2]],

       [[7, 6, 5, 8],
        [9, 5, 7, 9],
        [9, 8, 5, 8]],

       [[9, 5, 6, 8],
        [5, 6, 7, 7],
        [7, 9, 7, 9]]])

In [112]:
np.concatenate((arr1, arr2), axis=2)

array([[[2, 2, 2, 3, 7, 6, 5, 8],
        [3, 3, 3, 4, 9, 5, 7, 9],
        [1, 4, 2, 4, 9, 8, 5, 8]],

       [[4, 1, 3, 1, 9, 5, 6, 8],
        [1, 4, 4, 3, 5, 6, 7, 7],
        [1, 1, 2, 2, 7, 9, 7, 9]]])

In [113]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([8, 9, 10, 11, 12])

In [116]:
np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 12])

In [117]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [118]:
np.concatenate((arr1, arr2, arr3), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [119]:
np.concatenate((arr1, arr2, arr3), axis=1)

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

### 5. Splitting Arrays

In [120]:
arr = np.arange(1, 13).reshape((3, 4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
np.vsplit(arr, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [122]:
np.vsplit(arr, 3)[0]

array([[1, 2, 3, 4]])

In [123]:
np.vsplit(arr, 3)[0].shape

(1, 4)

In [125]:
np.vsplit(arr, [2])

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]])]

In [126]:
np.vsplit(arr, [2])[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
np.vsplit(arr, [2])[0].shape

(2, 4)

In [129]:
np.vsplit(arr, [2])[1]

array([[ 9, 10, 11, 12]])

In [130]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [133]:
np.hsplit(arr, 2)[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [134]:
np.hsplit(arr, [1, 3])

[array([[1],
        [5],
        [9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [135]:
np.hsplit(arr, [1, 3])[0]

array([[1],
       [5],
       [9]])

In [136]:
np.hsplit(arr, [1, 3])[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [137]:
np.hsplit(arr, [1, 3])[-1]

array([[ 4],
       [ 8],
       [12]])

### 6. Tiling Arrays

In [138]:
arr = np.array([1, 2])

In [143]:
np.tile(arr, (2, 4, 3))

array([[[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]],

       [[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]]])

In [144]:
arr = np.array([[1, 2], [3, 4]])

In [145]:
np.tile(arr, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [146]:
x = np.array([1, 2])
y = np.array([3, 4])

In [147]:
np.meshgrid(x, y)

(array([[1, 2],
        [1, 2]]),
 array([[3, 3],
        [4, 4]]))

### Exercise

In [148]:
sales_2021 = np.array([[100, 120, 140, 160],
                       [200, 220, 240, 260],
                       [300, 320, 340, 360]])

sales_2022 = np.array([[110, 130, 150, 170],
                       [210, 230, 250, 270],
                       [310, 330, 350, 370]])

In [149]:
# 1
combined_sales = np.vstack((sales_2021, sales_2022))
combined_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

In [150]:
# 2
combined_sales.reshape(-1)

array([100, 120, 140, 160, 200, 220, 240, 260, 300, 320, 340, 360, 110,
       130, 150, 170, 210, 230, 250, 270, 310, 330, 350, 370])

In [168]:
np.ravel(combined_sales)

array([100, 120, 140, 160, 200, 220, 240, 260, 300, 320, 340, 360, 110,
       130, 150, 170, 210, 230, 250, 270, 310, 330, 350, 370])

In [154]:
# 3
split_products = np.vsplit(combined_sales, 6)
split_products

[array([[100, 120, 140, 160]]),
 array([[200, 220, 240, 260]]),
 array([[300, 320, 340, 360]]),
 array([[110, 130, 150, 170]]),
 array([[210, 230, 250, 270]]),
 array([[310, 330, 350, 370]])]

In [156]:
product1_sales = np.concatenate((split_products[0], split_products[3]), axis=0)
product1_sales

array([[100, 120, 140, 160],
       [110, 130, 150, 170]])

In [157]:
product2_sales = np.concatenate((split_products[1], split_products[4]))
product2_sales

array([[200, 220, 240, 260],
       [210, 230, 250, 270]])

In [159]:
product3_sales = np.concatenate((split_products[2], split_products[5]))
product3_sales

array([[300, 320, 340, 360],
       [310, 330, 350, 370]])

In [165]:
# 4
repeated_sales = np.tile(combined_sales, (2, 1))
repeated_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370],
       [100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

In [166]:
# 5
total_sales_2021 = np.sum(sales_2021)
print(f"Total sales for 2021 was ${total_sales_2021} thousand dollars.")

Total sales for 2021 was $2760 thousand dollars.


In [167]:
total_sales_2022 = np.sum(sales_2022)
print(f"Total sales for 2022 was ${total_sales_2022} thousand dollars.")

Total sales for 2022 was $2880 thousand dollars.
